name: Docker Registry CI

on:
  push:
    branches: [main]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to dockerhub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: extract metadata tags from image (tags, label)
        id: meta
        uses: docker/metadata-action@v3.4.0
        with:
          images: tonydelacruz/jsonplaceholder-node:latest

      - name: Build and push docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
